CREATE SEQUENCE SQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE tbl_usuarios (
    usuarioId INTEGER DEFAULT SQ_USUARIOS.NEXTVAL NOT NULL,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(35) NOT NULL,
    senha VARCHAR(35) NOT NULL,
    role VARCHAR(7) DEFAULT 'user' NOT NULL
);
